In [1]:
import numpy as np

# NumPy Constants

In [2]:
print('Inifinity (neg,pos): ({0},{1})'.format(np.NINF,np.inf))
print('Zero (neg,pos): ({0},{1})'.format(np.NZERO,np.PZERO))
print('Pi: {0}\nEuler Gamma: {1}\nEpsilon e: {2}'.format(np.pi,np.euler_gamma,np.e))
print('NotANumber: {0}'.format(np.nan))

Inifinity (neg,pos): (-inf,inf)
Zero (neg,pos): (-0.0,0.0)
Pi: 3.141592653589793
Euler Gamma: 0.5772156649015329
Epsilon e: 2.718281828459045
NotANumber: nan


# Array: A collection of similar data types

In [3]:
## Create an N dimensional array with random values
ax = np.empty([3,3], np.uint16)
ax

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 3]], dtype=uint16)

In [4]:
# To generate a desired array with random numbers less than 1 used if noise must be introduced
randArr = np.random.rand(3,3,3)
randArr

array([[[0.73431092, 0.69454973, 0.97161082],
        [0.55261368, 0.34743391, 0.6567429 ],
        [0.93888425, 0.98814134, 0.71430311]],

       [[0.16426065, 0.80144068, 0.92779179],
        [0.15948604, 0.80363089, 0.22510073],
        [0.25949142, 0.14746113, 0.44482087]],

       [[0.00735536, 0.39277005, 0.98375175],
        [0.52578463, 0.69002365, 0.19788485],
        [0.00498003, 0.07873758, 0.64750434]]])

In [5]:
print('size: {0}\nshape: {1}'.format(randArr.size,randArr.shape))

size: 27
shape: (3, 3, 3)


In [6]:
## Create an array with the diagnol as 1
bx = np.eye(5,dtype=np.uint8) 
bx
## Similar to the below
# bx = np.identity(5,dtype=np.uint8) 
# bx

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [7]:
#To change the position of 1
bx1 = np.eye(5, dtype=np.uint8 , k=1)
bx1

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [8]:
#To change the position of 1 down
bx1a = np.eye(5, dtype=np.uint8 , k=-1)
bx1a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [9]:
## To create N dimentional matrix with elements as 1
all1 = np.ones((3,3,5))
all1

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
## To create N dimentional matrix with elements as 0
all0= np.zeros((3,3,5))
all0

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
## To create N dimentional matrix with desired elements
allD = np.full((3,3,3),dtype=np.uint8,fill_value=7)
allD

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]], dtype=uint8)

In [12]:
## Create a Triangular Matrix
tri1 = np.tri(5,5,k=0)
tri1

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [13]:
## Upper Triangle
ut = np.triu(ax,k=0)
ut

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 3]], dtype=uint16)

In [14]:
## Lower Triangle
lt = np.tril(ax,k=0)
lt

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 3]], dtype=uint16)

Creation of custom arrays

In [15]:
# Creating a unidirectional array with int16 datatype
x = np.array([1,'2',3,4,5, 6] , np.int8)
x # is equalent to x.view()

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [16]:
print(x[1])
print(x[1].dtype)

2
int8


In [17]:
## shows how many dimensions are there  in the array
x.ndim

1

In [18]:
## Transpose of the matrix
x.T

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [19]:
x2 = np.array([[1,2,3,4,5], [6,7,8,9,10]], np.int8)
x2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

In [20]:
x2.ndim

2

In [21]:
# The data type of internal elements of the array
x2.dtype

dtype('int8')

The number of '[]' mentioned inside the array() method will decide the dimensions of the array, i.e for 
n number of dimensions use nnumber of []

In [22]:
x2.view()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

In [23]:
x2.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]], dtype=int8)

access values with nameofArray[ROWS,COLLUMNS]

In [24]:
# To access the elements of the array, 
print('First row of the array:  {0}\nSecond row of the array: {1}\nits type is {2}'.format(x2[0],x2[1],type(x2[0])))

First row of the array:  [1 2 3 4 5]
Second row of the array: [ 6  7  8  9 10]
its type is <class 'numpy.ndarray'>


In [25]:
## Printing the forth element of second row.
print('Access Method 1 x2[1,3]:  {0}\nAccess Method 2 x2[1][3]: {1}\nAccess Method 3 x2[[1],[3]]: {2}'.format(x2[1,3],x2[1][3],x2[[1],[3]]))
print('Access Type 1:  {0}\nAccess Type 2: {1}\nAccess Type 3: {2}'.format(type(x2[1,3]) , type(x2[1][3]) , type(x2[[1],[3]]) ))

Access Method 1 x2[1,3]:  9
Access Method 2 x2[1][3]: 9
Access Method 3 x2[[1],[3]]: [9]
Access Type 1:  <class 'numpy.int8'>
Access Type 2: <class 'numpy.int8'>
Access Type 3: <class 'numpy.ndarray'>


Slicing data from Array Objects

In [26]:
## Printing the forth element of second row.
print('Access Method 1 x2[1,3]:  {0}\nAccess Method 2 x2[1][3]: {1}\nAccess Method 3 x2[[1],[3]]: {2}'.format(x2[1,3],x2[1][3],x2[[1],[3]]))
print('Access Type 1:  {0}\nAccess Type 2: {1}\nAccess Type 3: {2}'.format(type(x2[1,3]) , type(x2[1][3]) , type(x2[[1],[3]]) ))

Access Method 1 x2[1,3]:  9
Access Method 2 x2[1][3]: 9
Access Method 3 x2[[1],[3]]: [9]
Access Type 1:  <class 'numpy.int8'>
Access Type 2: <class 'numpy.int8'>
Access Type 3: <class 'numpy.ndarray'>


In [27]:
#to print the  first column of the array
x2[:,0]

array([1, 6], dtype=int8)

In [28]:
# Second column
x2[:,1]

array([2, 7], dtype=int8)

In [29]:
#To print the entire first row
x2[0,:]

array([1, 2, 3, 4, 5], dtype=int8)

In [30]:
# To print an element of Second row fourth column
x2[1,3]

9

In [31]:
# To print the elements of first row from second element to fourth element
x2[0,1:4]

array([2, 3, 4], dtype=int8)

In [32]:
# To print the elements of array from all the rows but column 2 to 4
x2[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]], dtype=int8)

In [33]:
## Shape gives rows,columns value
x2.shape

(2, 5)

In [34]:
xNOT3D = np.array([[1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]], np.int8)
xNOT3D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]], dtype=int8)

In [35]:
print('Dimensions: {0}\nShape: {1}'.format(xNOT3D.ndim,xNOT3D.shape))

Dimensions: 2
Shape: (3, 5)


In [36]:
x3 = np.array(
    [
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15] 
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ]
    ]
    , np.int8)
x3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[11, 12, 13, 14, 15],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [ 1,  2,  3,  4,  5]]], dtype=int8)

In [37]:
print('Dimensions: {0}\nShape: {1}'.format(x3.ndim,x3.shape))

Dimensions: 3
Shape: (3, 3, 5)


In [38]:
## Print 12 from all the dimensions
print('From Dim 1 x3[0,2,1]: {0}\nFrom Dim 2 x3[1,0,1]: {1}\nFrom Dim 3 x3[2,1,1]: {2}'.format(x3[0,2,1],x3[1,0,1],x3[2,1,1]))

From Dim 1 x3[0,2,1]: 12
From Dim 2 x3[1,0,1]: 12
From Dim 3 x3[2,1,1]: 12


In [39]:
x3[0,:,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]], dtype=int8)

In [40]:
x3[:,:,0:3]

array([[[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]],

       [[11, 12, 13],
        [ 1,  2,  3],
        [ 6,  7,  8]],

       [[ 6,  7,  8],
        [11, 12, 13],
        [ 1,  2,  3]]], dtype=int8)

In [41]:
x3[:,:,1:2]

array([[[ 2],
        [ 7],
        [12]],

       [[12],
        [ 2],
        [ 7]],

       [[ 7],
        [12],
        [ 2]]], dtype=int8)

In [42]:
x3[:,:,1:2][2]

array([[ 7],
       [12],
       [ 2]], dtype=int8)

In [43]:
x3[:,:,1:2][2][0]

array([7], dtype=int8)

In [44]:
x3.T

array([[[ 1, 11,  6],
        [ 6,  1, 11],
        [11,  6,  1]],

       [[ 2, 12,  7],
        [ 7,  2, 12],
        [12,  7,  2]],

       [[ 3, 13,  8],
        [ 8,  3, 13],
        [13,  8,  3]],

       [[ 4, 14,  9],
        [ 9,  4, 14],
        [14,  9,  4]],

       [[ 5, 15, 10],
        [10,  5, 15],
        [15, 10,  5]]], dtype=int8)

In [45]:
x4 = np.array(
    
[    [
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],

    [
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],
    
[
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],
    
[
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ]   
    
    ]
)

x4

array([[[[list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])],
         [list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
          list([11, 12, 13, 14, 15])],
         [list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
          list([6, 7, 8, 9, 10])],
         [list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
          list([1, 2, 3, 4, 5])],
         [list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])]],

        [[list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])],
         [list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
          list([11, 12, 13, 14, 15])],
         [list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
          list([6, 7, 8, 9, 10])],
         [list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
          list([1, 2, 3, 4, 5])],
         [list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 3

In [46]:
print('Dimensions: {0}\nShape: {1}\nSize[no of elements in array] :{2}\nMemory Consumption in Bytes(dtype*size): {3}'.format(x4.ndim,x4.shape,x4.size,x4.nbytes))

Dimensions: 4
Shape: (4, 4, 5, 3)
Size[no of elements in array] :240
Memory Consumption in Bytes(dtype*size): 1920


In [47]:
# To reach an element inside x4
x4[1,1,1,1][1]

7

Array Manipulation

In [48]:
ar1 = np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
ar2 = ar1.reshape((5,2))
ar2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
# Flattening the matrix/Array [mostly used in signal processing and image processing]
# flatten(...)
#  |      a.flatten(order='C')
#  |      
#  |      Return a copy of the array collapsed into one dimension.
#  |      
#  |      Parameters
#  |      ----------
#  |      order : {'C', 'F', 'A', 'K'}, optional
#  |          'C' means to flatten in row-major (C-style) order.
#  |          'F' means to flatten in column-major (Fortran-
#  |          style) order. 'A' means to flatten in column-major
#  |          order if `a` is Fortran *contiguous* in memory,
#  |          row-major order otherwise. 'K' means to flatten
#  |          `a` in the order the elements occur in memory.
#  |          The default is 'C'.
fl1 = ar2.flatten()
fl1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
fl1.ndim

1

In [52]:
fl2 = x4.flatten()
fl2

array([list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
       list([31, 32, 33, 34, 35]), list([1, 2, 3, 4, 5]),
       list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
       list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
       list([6, 7, 8, 9, 10]), list([6, 7, 8, 9, 10]),
       list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
       list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
       list([31, 32, 33, 34, 35]), list([20, 21, 22, 23, 24]),
       list([25, 26, 27, 28, 29, 30]), list([31, 32, 33, 34, 35]),
       list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
       list([11, 12, 13, 14, 15]), list([11, 12, 13, 14, 15]),
       list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
       list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
       list([1, 2, 3, 4, 5]), list([20, 21, 22, 23, 24]),
       list([25, 26, 27, 28, 29, 30]), list([31, 32, 33, 34, 35]),
       list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
       list([31, 32, 33, 3

In [53]:
fl2.ndim

1

In [54]:
xaf = np.array([[1,2,3],[4,5,6]], order='F')
xaf

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
xac = np.array([[1,2,3],[4,5,6]], order='C')
xac

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
xaf == xac

array([[ True,  True,  True],
       [ True,  True,  True]])

In [57]:
id(xaf) == id(xac)

False

In [58]:
## Merging two Series or lists and making them into arrays
vecVal1 = np.arange(6)
vecVal2 = np.arange(6,12)
print(vecVal1,vecVal2, 'type: {0}'.format(type(vecVal1)))

[0 1 2 3 4 5] [ 6  7  8  9 10 11] type: <class 'numpy.ndarray'>


In [59]:
RStk = np.stack([vecVal1, vecVal2], axis=0)
RStk

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [60]:
CStk = np.stack([vecVal1, vecVal2], axis=1)
print('Matrisx: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(CStk,type(CStk),CStk.ndim,CStk.shape,CStk.size))

Matrisx: 
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
Type: <class 'numpy.ndarray'>
Dimensions: 2
Shape: (6, 2)
Size: 12


In [61]:
# To stack the data in multiple ergonomic way D-Stack
DStk = np.dstack([vecVal1, vecVal2])
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(DStk,type(DStk),DStk.ndim,DStk.shape,DStk.size))

Matrix: 
[[[ 0  6]
  [ 1  7]
  [ 2  8]
  [ 3  9]
  [ 4 10]
  [ 5 11]]]
Type: <class 'numpy.ndarray'>
Dimensions: 3
Shape: (1, 6, 2)
Size: 12


In [62]:
#Stacking everything Horizontally
HStk = np.hstack([vecVal1, vecVal2])
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(HStk,type(HStk),HStk.ndim,HStk.shape,HStk.size))

Matrix: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Type: <class 'numpy.ndarray'>
Dimensions: 1
Shape: (12,)
Size: 12


In [63]:
VStk = np.vstack([vecVal1, vecVal2])
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(VStk,type(VStk),VStk.ndim,VStk.shape,VStk.size))

Matrix: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Type: <class 'numpy.ndarray'>
Dimensions: 2
Shape: (2, 6)
Size: 12


In [64]:
randArray1 = np.random.rand(4,4,4)
randArray1

array([[[0.91777882, 0.84068607, 0.45749073, 0.22380792],
        [0.182047  , 0.97898376, 0.48470782, 0.97526069],
        [0.78325789, 0.73118427, 0.28001838, 0.39514943],
        [0.69453263, 0.20882112, 0.30085553, 0.7351615 ]],

       [[0.66688071, 0.2512307 , 0.49295583, 0.70642739],
        [0.43316812, 0.48181128, 0.57629706, 0.70399387],
        [0.87228206, 0.5024881 , 0.00241244, 0.83536672],
        [0.85960587, 0.33680156, 0.65061774, 0.73869582]],

       [[0.85794219, 0.55516374, 0.6004701 , 0.56233252],
        [0.31244028, 0.00424396, 0.40678073, 0.77256869],
        [0.16956219, 0.7660012 , 0.04165779, 0.27330116],
        [0.44163912, 0.96569878, 0.24195956, 0.11108548]],

       [[0.0984262 , 0.26592246, 0.3635443 , 0.1146214 ],
        [0.6011081 , 0.12440823, 0.97892592, 0.20229005],
        [0.72963234, 0.44111818, 0.78410562, 0.95157501],
        [0.09562839, 0.32476753, 0.94370859, 0.35217014]]])

In [65]:
## Spliting data into equal parts mostly of the data is in divedents of 2
a,b,c,d = np.split(HStk,4)
print(a,b,c,d)

[0 1 2] [3 4 5] [6 7 8] [ 9 10 11]


In [66]:
a,b,c,d = np.hsplit(randArray1,4)
print(a,b,c,d)

[[[0.91777882 0.84068607 0.45749073 0.22380792]]

 [[0.66688071 0.2512307  0.49295583 0.70642739]]

 [[0.85794219 0.55516374 0.6004701  0.56233252]]

 [[0.0984262  0.26592246 0.3635443  0.1146214 ]]] [[[0.182047   0.97898376 0.48470782 0.97526069]]

 [[0.43316812 0.48181128 0.57629706 0.70399387]]

 [[0.31244028 0.00424396 0.40678073 0.77256869]]

 [[0.6011081  0.12440823 0.97892592 0.20229005]]] [[[0.78325789 0.73118427 0.28001838 0.39514943]]

 [[0.87228206 0.5024881  0.00241244 0.83536672]]

 [[0.16956219 0.7660012  0.04165779 0.27330116]]

 [[0.72963234 0.44111818 0.78410562 0.95157501]]] [[[0.69453263 0.20882112 0.30085553 0.7351615 ]]

 [[0.85960587 0.33680156 0.65061774 0.73869582]]

 [[0.44163912 0.96569878 0.24195956 0.11108548]]

 [[0.09562839 0.32476753 0.94370859 0.35217014]]]


In [67]:
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(a,type(a),a.ndim,a.shape,a.size))

Matrix: 
[[[0.91777882 0.84068607 0.45749073 0.22380792]]

 [[0.66688071 0.2512307  0.49295583 0.70642739]]

 [[0.85794219 0.55516374 0.6004701  0.56233252]]

 [[0.0984262  0.26592246 0.3635443  0.1146214 ]]]
Type: <class 'numpy.ndarray'>
Dimensions: 3
Shape: (4, 1, 4)
Size: 16


In [68]:
a,b,c,d = np.vsplit(randArray1,4)
print(a,b,c,d)

[[[0.91777882 0.84068607 0.45749073 0.22380792]
  [0.182047   0.97898376 0.48470782 0.97526069]
  [0.78325789 0.73118427 0.28001838 0.39514943]
  [0.69453263 0.20882112 0.30085553 0.7351615 ]]] [[[0.66688071 0.2512307  0.49295583 0.70642739]
  [0.43316812 0.48181128 0.57629706 0.70399387]
  [0.87228206 0.5024881  0.00241244 0.83536672]
  [0.85960587 0.33680156 0.65061774 0.73869582]]] [[[0.85794219 0.55516374 0.6004701  0.56233252]
  [0.31244028 0.00424396 0.40678073 0.77256869]
  [0.16956219 0.7660012  0.04165779 0.27330116]
  [0.44163912 0.96569878 0.24195956 0.11108548]]] [[[0.0984262  0.26592246 0.3635443  0.1146214 ]
  [0.6011081  0.12440823 0.97892592 0.20229005]
  [0.72963234 0.44111818 0.78410562 0.95157501]
  [0.09562839 0.32476753 0.94370859 0.35217014]]]


In [69]:
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(a,type(a),a.ndim,a.shape,a.size))

Matrix: 
[[[0.91777882 0.84068607 0.45749073 0.22380792]
  [0.182047   0.97898376 0.48470782 0.97526069]
  [0.78325789 0.73118427 0.28001838 0.39514943]
  [0.69453263 0.20882112 0.30085553 0.7351615 ]]]
Type: <class 'numpy.ndarray'>
Dimensions: 3
Shape: (1, 4, 4)
Size: 16


In [70]:
a

array([[[0.91777882, 0.84068607, 0.45749073, 0.22380792],
        [0.182047  , 0.97898376, 0.48470782, 0.97526069],
        [0.78325789, 0.73118427, 0.28001838, 0.39514943],
        [0.69453263, 0.20882112, 0.30085553, 0.7351615 ]]])

In [71]:
## It litraly flips as per the axis: -ve(Ndim - 1),+ve(Ndim - 1)
np.flip(a, axis=1)

array([[[0.69453263, 0.20882112, 0.30085553, 0.7351615 ],
        [0.78325789, 0.73118427, 0.28001838, 0.39514943],
        [0.182047  , 0.97898376, 0.48470782, 0.97526069],
        [0.91777882, 0.84068607, 0.45749073, 0.22380792]]])

In [72]:
np.flip(a, axis=-1)

array([[[0.22380792, 0.45749073, 0.84068607, 0.91777882],
        [0.97526069, 0.48470782, 0.97898376, 0.182047  ],
        [0.39514943, 0.28001838, 0.73118427, 0.78325789],
        [0.7351615 , 0.30085553, 0.20882112, 0.69453263]]])

In [73]:
b

array([[[0.66688071, 0.2512307 , 0.49295583, 0.70642739],
        [0.43316812, 0.48181128, 0.57629706, 0.70399387],
        [0.87228206, 0.5024881 , 0.00241244, 0.83536672],
        [0.85960587, 0.33680156, 0.65061774, 0.73869582]]])

In [74]:
## Swaps the bottom most N elements to up
np.roll(b,4)

array([[[0.85960587, 0.33680156, 0.65061774, 0.73869582],
        [0.66688071, 0.2512307 , 0.49295583, 0.70642739],
        [0.43316812, 0.48181128, 0.57629706, 0.70399387],
        [0.87228206, 0.5024881 , 0.00241244, 0.83536672]]])

In [75]:
# BitWise Opperations
x = np.array([0,1,0,1], np.uint8)
y = np.array([0,0,1,1], np.uint8)

print(np.bitwise_and(x,y))
print(np.bitwise_or(x,y))
print(np.bitwise_xor(x,y))
print(np.bitwise_not(y))

[0 0 0 1]
[0 1 1 1]
[0 1 1 0]
[255 255 254 254]


# Statistical and Arthematic Calculation

In [76]:
randArr = np.random.randint(10,100,10)
randArr

array([24, 32, 15, 36, 72, 55, 41, 41, 77, 20])

In [77]:
print('Mean: {0}\nMedian: {1}\nAverage: {2}\nStandard_Deviation: {3}\nVariance: {4}'.format(
    np.mean(randArr),
    np.median(randArr),
    np.average(randArr),
    np.std(randArr),
    np.var(randArr)))

Mean: 41.3
Median: 38.5
Average: 41.3
Standard_Deviation: 19.91004771465905
Variance: 396.41


In [78]:
np.histogram(randArr)

(array([2, 1, 1, 1, 2, 0, 1, 0, 0, 2], dtype=int64),
 array([15. , 21.2, 27.4, 33.6, 39.8, 46. , 52.2, 58.4, 64.6, 70.8, 77. ]))

# Dot Product
--> Array should always be 2 Dimensional to execute dot product.

            <!-- e = np.linalg.multi_dot([a,b,c,d])
                        print(e) -->
                        Will throw the below error
LinAlgError                               Traceback (most recent call last)
<ipython-input-80-66f087b1270d> in <module>
      1 # Array should always be 2 Dimensional to execute dot product
----> 2 e = np.linalg.multi_dot([a,b,c,d])
      3 e

<__array_function__ internals> in multi_dot(*args, **kwargs)

c:\program files\python37\lib\site-packages\numpy\linalg\linalg.py in multi_dot(arrays)
   2658     if arrays[-1].ndim == 1:
   2659         arrays[-1] = atleast_2d(arrays[-1]).T
-> 2660     _assert_2d(*arrays)
   2661 
   2662     # _multi_dot_three is much faster than _multi_dot_matrix_chain_order

c:\program files\python37\lib\site-packages\numpy\linalg\linalg.py in _assert_2d(*arrays)
    199         if a.ndim != 2:
    200             raise LinAlgError('%d-dimensional array given. Array must be '
--> 201                     'two-dimensional' % a.ndim)
    202 
    203 def _assert_stacked_2d(*arrays):

LinAlgError: 3-dimensional array given. Array must be two-dimensional


In [79]:
##Equal size gives out equal original length
a = np.random.rand(3,3)
b = np.random.rand(3,3)
print('a:\n{0}\nDIM: {1}\n-----------------\n'.format(a,a.shape))
print('b:\n{0}\nDIM: {1}\n-----------------\n'.format(b,b.shape))
c = np.dot(a,b)
print('c:\n{0}\nDIM: {1}\nDot Product\n'.format(c,c.shape))

a:
[[0.2332446  0.67379963 0.06810032]
 [0.36056905 0.35622203 0.4794675 ]
 [0.43790023 0.93753285 0.87739489]]
DIM: (3, 3)
-----------------

b:
[[0.60370021 0.64121573 0.98945431]
 [0.81625767 0.66653825 0.73469933]
 [0.2739682  0.84982048 0.10658646]]
DIM: (3, 3)
-----------------

c:
[[0.70946125 0.65654638 0.73308358]
 [0.63980343 0.87609946 0.66958743]
 [1.27000714 1.65131817 1.21560544]]
DIM: (3, 3)
Dot Product



In [80]:
## Unequal length gives the Highest possible matrix shape
a = np.random.rand(5,3)
b = np.random.rand(3,3)
print('a:\n{0}\nDIM: {1}\n-----------------\n'.format(a,a.shape))
print('b:\n{0}\nDIM: {1}\n-----------------\n'.format(b,b.shape))
d = np.dot(a,b)
print('c:\n{0}\nDIM: {1}\nDot Product\n'.format(d,d.shape))

a:
[[0.77286043 0.61451827 0.28872376]
 [0.73459485 0.70481962 0.16960319]
 [0.9978127  0.08817586 0.5568824 ]
 [0.18789536 0.15841896 0.00316382]
 [0.55061983 0.66257528 0.363117  ]]
DIM: (5, 3)
-----------------

b:
[[0.76756662 0.71055889 0.78642586]
 [0.30856238 0.48158812 0.39302238]
 [0.03173254 0.78160611 0.8372476 ]]
DIM: (3, 3)
-----------------

c:
[[0.79200103 1.07077581 1.09105014]
 [0.78671324 0.99396855 0.99671414]
 [0.81076676 1.18673182 1.28560925]
 [0.19320473 0.21227627 0.21267686]
 [0.63860583 0.99415066 0.99744742]]
DIM: (5, 3)
Dot Product



In [81]:
a = np.random.rand(5,3)
b = np.random.rand(3,1)
print('a:\n{0}\nDIM: {1}\n-----------------\n'.format(a,a.shape))
print('b:\n{0}\nDIM: {1}\n-----------------\n'.format(b,b.shape))
e = np.dot(a,b)
print('c:\n{0}\nDIM: {1}\nDot Product\n'.format(e,e.shape))

a:
[[0.82030995 0.71882112 0.20535289]
 [0.47372342 0.03390547 0.33395692]
 [0.18454933 0.61036278 0.7761807 ]
 [0.67808356 0.15761609 0.84283199]
 [0.45419218 0.70828142 0.42828919]]
DIM: (5, 3)
-----------------

b:
[[0.5858466 ]
 [0.34176269]
 [0.19892214]]
DIM: (3, 1)
-----------------

c:
[[0.76709127]
 [0.3555483 ]
 [0.47111634]
 [0.61877819]
 [0.59334731]]
DIM: (5, 1)
Dot Product



                            <!-- a = np.random.rand(5,1)
                            b = np.random.rand(3,3)
                            print('a:\n{0}\nDIM: {1}\n-----------------\n'.format(a,a.shape))
                            print('b:\n{0}\nDIM: {1}\n-----------------\n'.format(b,b.shape))
                            c = np.dot(a,b)
                            print('c:\n{0}\nDIM: {1}\nDot Product\n'.format(c,c.shape))
                             -->
The number of colums in the first matrix should match with the no of rows in second
ValueError                                Traceback (most recent call last)
<ipython-input-104-53d9a6edb776> in <module>
      3 print('a:\n{0}\nDIM: {1}\n-----------------\n'.format(a,a.shape))
      4 print('b:\n{0}\nDIM: {1}\n-----------------\n'.format(b,b.shape))
----> 5 c = np.dot(a,b)
      6 print('c:\n{0}\nDIM: {1}\nDot Product\n'.format(c,c.shape))

<__array_function__ internals> in dot(*args, **kwargs)

ValueError: shapes (5,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

While doing a Multi dot product oprtation, it works only if the number of colums's in dirst matrix is equal to number of rowa in second matris
f = np.linalg.multi_dot([d,e,c])
        else we would get below error

ValueError                                Traceback (most recent call last)
<ipython-input-111-be0a13f13e25> in <module>
----> 1 f = np.linalg.multi_dot([d,e,c])

<__array_function__ internals> in multi_dot(*args, **kwargs)

c:\program files\python37\lib\site-packages\numpy\linalg\linalg.py in multi_dot(arrays)
   2662     # _multi_dot_three is much faster than _multi_dot_matrix_chain_order
   2663     if n == 3:
-> 2664         result = _multi_dot_three(arrays[0], arrays[1], arrays[2])
   2665     else:
   2666         order = _multi_dot_matrix_chain_order(arrays)

c:\program files\python37\lib\site-packages\numpy\linalg\linalg.py in _multi_dot_three(A, B, C)
   2694         return dot(dot(A, B), C)
   2695     else:
-> 2696         return dot(A, dot(B, C))
   2697 
   2698 

<__array_function__ internals> in dot(*args, **kwargs)

ValueError: shapes (5,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)


In [82]:
## In the below example we could see that the Column length of first matrix is equal to Row length of second. 
a = np.random.rand(5,10)
b = np.random.rand(10,7)
c = np.random.rand(7,3)
d = np.random.rand(3,5)
e = np.random.rand(5,2)
f = np.random.rand(2,3)

g = np.linalg.multi_dot([a,b,c,d,e,f])

print('Matrix G: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(g,type(g),g.ndim,g.shape,g.size))

Matrix G: 
[[27.16429269  6.01424165 30.07121142]
 [42.35857611  9.37839989 46.89370944]
 [44.79026595  9.91677975 49.58557211]
 [41.95110155  9.28821701 46.44332413]
 [43.55476697  9.64332652 48.21973849]]
Type: <class 'numpy.ndarray'>
Dimensions: 2
Shape: (5, 3)
Size: 15


# Vector Product

The rules of dot would not apply for Vector. 'vdot' method is specifically designed for single dimension vector but not matrices or arrays, can also work for list, series object

                       1. <!-- VectorG = np.vdot(a,b) -->

ValueError                                Traceback (most recent call last)
<ipython-input-85-a005b0a41e6b> in <module>
----> 1 VectorG = np.vdot(a,b)

<__array_function__ internals> in vdot(*args, **kwargs)

ValueError: cannot reshape array of size 70 into shape (50,)

In [92]:
a = np.random.randint(1,10,12)
b = np.random.randint(11,20,12)
c = np.vdot(a,b)
print('a: {0}\nb: {1}\nc: {2}\nc.Shape: {3}'.format(a,b,c,c.size))

a: [3 7 1 2 3 5 3 4 5 5 7 2]
b: [11 17 15 16 11 13 16 12 14 17 17 17]
c: 701
c.Shape: 1


In [93]:
a = np.array([ 1 + 5j , 10 + 12j])
b = np.array([ 11 + 20j , 12 + 1j])
c = np.vdot(a,b)
d = np.vdot(b,a)
print('a: {0}\nb: {1}\nc: {2}\nc.Shape: {3}'.format(a,b,c,c.size))
print('\nd: {0}\nd.Shape: {1}'.format(c,c.size))

a: [ 1. +5.j 10.+12.j]
b: [11.+20.j 12. +1.j]
c: (243-169j)
c.Shape: 1

d: (243-169j)
d.Shape: 1


In [111]:
# Inner Product
a = [1,1]
b = [1,1]
c = np.inner(a,b)
c

2

In [126]:
#Decomposition [dividing a matrix into two equal parts]
a = np.array([[0.85673336, 0.59184079, 0.51127339], [0.72309976, 0.2895832,  0.59275445], [0.31351627, 0.35795678, 0.52398562]])
print('a: {0}\n'.format(a))
q,r = np.linalg.qr(a)
print('\nq: {0}\n\nr: {1}'.format(q,r))

a: [[0.85673336 0.59184079 0.51127339]
 [0.72309976 0.2895832  0.59275445]
 [0.31351627 0.35795678 0.52398562]]


q: [[-0.73595413  0.28834405 -0.61255957]
 [-0.62115972 -0.64748415  0.44150297]
 [-0.26931786  0.70542327  0.65562635]]

r: [[-1.16411244 -0.71184925 -0.88558764]
 [ 0.          0.23566428  0.13325517]
 [ 0.          0.          0.29205622]]


In [168]:
a = np.array([[-14840,  26481,    659],
       [     0, -12728,  26481],
       [   659,      0, -14904]], np.int16)
print('a: {0}\n'.format(a))
q,r = np.linalg.qr(a)
print('\nq: {0}\n\nr: {1}'.format(q,r))

a: [[-14840  26481    659]
 [     0 -12728  26481]
 [   659      0 -14904]]


q: [[-0.99901546  0.00407737  0.04417552]
 [ 0.         -0.99576745  0.09190854]
 [ 0.04436329  0.09181805  0.99478708]]

r: [[ 14854.6249027  -26454.92852051  -1319.54163288]
 [     0.          12782.10084355 -27734.68719398]
 [     0.              0.         -12363.36500031]]
