In [1]:
import numpy as np

# NumPy Constants

In [2]:
print('Inifinity (neg,pos): ({0},{1})'.format(np.NINF,np.inf))
print('Zero (neg,pos): ({0},{1})'.format(np.NZERO,np.PZERO))
print('Pi: {0}\nEuler Gamma: {1}\nEpsilon e: {2}'.format(np.pi,np.euler_gamma,np.e))
print('NotANumber: {0}'.format(np.nan))

Inifinity (neg,pos): (-inf,inf)
Zero (neg,pos): (-0.0,0.0)
Pi: 3.141592653589793
Euler Gamma: 0.5772156649015329
Epsilon e: 2.718281828459045
NotANumber: nan


# Array: A collection of similar data types

In [3]:
## Create an N dimensional array with random values
ax = np.empty([3,3], np.int)
ax

array([[6881399, 7536750, 7274608],
       [7077999, 6553646, 7733362],
       [      0,       0,       0]])

In [4]:
## Create an array with the diagnol as 1
bx = np.eye(5,dtype=np.uint8) 
bx
## Similar to the below
# bx = np.identity(5,dtype=np.uint8) 
# bx

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [5]:
#To change the position of 1
bx1 = np.eye(5, dtype=np.uint8 , k=1)
bx1

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [6]:
#To change the position of 1 down
bx1a = np.eye(5, dtype=np.uint8 , k=-1)
bx1a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [7]:
## To create N dimentional matrix with elements as 1
all1 = np.ones((3,3,5))
all1

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [8]:
## To create N dimentional matrix with elements as 0
all0= np.zeros((3,3,5))
all0

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
## To create N dimentional matrix with desired elements
allD = np.full((3,3,3),dtype=np.uint8,fill_value=7)
allD

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]], dtype=uint8)

In [11]:
## Create a Triangular Matrix
tri1 = np.tri(5,5,k=0)
tri1

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [12]:
## Upper Triangle
ut = np.triu(ax,k=0)
ut

array([[6881399, 7536750, 7274608],
       [      0, 6553646, 7733362],
       [      0,       0,       0]])

In [13]:
## Lower Triangle
lt = np.tril(ax,k=0)
lt

array([[6881399,       0,       0],
       [7077999, 6553646,       0],
       [      0,       0,       0]])

Creation of custom arrays

In [14]:
# Creating a unidirectional array with int16 datatype
x = np.array([1,'2',3,4,5, 6] , np.int8)
x # is equalent to x.view()

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [15]:
print(x[1])
print(x[1].dtype)

2
int8


In [16]:
## shows how many dimensions are there  in the array
x.ndim

1

In [17]:
## Transpose of the matrix
x.T

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [18]:
x2 = np.array([[1,2,3,4,5], [6,7,8,9,10]], np.int8)
x2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

In [19]:
x2.ndim

2

In [20]:
# The data type of internal elements of the array
x2.dtype

dtype('int8')

The number of '[]' mentioned inside the array() method will decide the dimensions of the array, i.e for 
n number of dimensions use nnumber of []

In [21]:
x2.view()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

In [22]:
x2.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]], dtype=int8)

access values with nameofArray[ROWS,COLLUMNS]

In [23]:
# To access the elements of the array, 
print('First row of the array:  {0}\nSecond row of the array: {1}\nits type is {2}'.format(x2[0],x2[1],type(x2[0])))

First row of the array:  [1 2 3 4 5]
Second row of the array: [ 6  7  8  9 10]
its type is <class 'numpy.ndarray'>


In [24]:
## Printing the forth element of second row.
print('Access Method 1 x2[1,3]:  {0}\nAccess Method 2 x2[1][3]: {1}\nAccess Method 3 x2[[1],[3]]: {2}'.format(x2[1,3],x2[1][3],x2[[1],[3]]))
print('Access Type 1:  {0}\nAccess Type 2: {1}\nAccess Type 3: {2}'.format(type(x2[1,3]) , type(x2[1][3]) , type(x2[[1],[3]]) ))

Access Method 1 x2[1,3]:  9
Access Method 2 x2[1][3]: 9
Access Method 3 x2[[1],[3]]: [9]
Access Type 1:  <class 'numpy.int8'>
Access Type 2: <class 'numpy.int8'>
Access Type 3: <class 'numpy.ndarray'>


Slicing data from Array Objects

In [25]:
## Printing the forth element of second row.
print('Access Method 1 x2[1,3]:  {0}\nAccess Method 2 x2[1][3]: {1}\nAccess Method 3 x2[[1],[3]]: {2}'.format(x2[1,3],x2[1][3],x2[[1],[3]]))
print('Access Type 1:  {0}\nAccess Type 2: {1}\nAccess Type 3: {2}'.format(type(x2[1,3]) , type(x2[1][3]) , type(x2[[1],[3]]) ))

Access Method 1 x2[1,3]:  9
Access Method 2 x2[1][3]: 9
Access Method 3 x2[[1],[3]]: [9]
Access Type 1:  <class 'numpy.int8'>
Access Type 2: <class 'numpy.int8'>
Access Type 3: <class 'numpy.ndarray'>


In [26]:
#to print the  first column of the array
x2[:,0]

array([1, 6], dtype=int8)

In [27]:
# Second column
x2[:,1]

array([2, 7], dtype=int8)

In [28]:
#To print the entire first row
x2[0,:]

array([1, 2, 3, 4, 5], dtype=int8)

In [29]:
# To print an element of Second row fourth column
x2[1,3]

9

In [30]:
# To print the elements of first row from second element to fourth element
x2[0,1:4]

array([2, 3, 4], dtype=int8)

In [31]:
# To print the elements of array from all the rows but column 2 to 4
x2[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]], dtype=int8)

In [32]:
## Shape gives rows,columns value
x2.shape

(2, 5)

In [33]:
xNOT3D = np.array([[1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]], np.int8)
xNOT3D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]], dtype=int8)

In [34]:
print('Dimensions: {0}\nShape: {1}'.format(xNOT3D.ndim,xNOT3D.shape))

Dimensions: 2
Shape: (3, 5)


In [35]:
x3 = np.array(
    [
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15] 
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ]
    ]
    , np.int8)
x3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[11, 12, 13, 14, 15],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [ 1,  2,  3,  4,  5]]], dtype=int8)

In [36]:
print('Dimensions: {0}\nShape: {1}'.format(x3.ndim,x3.shape))

Dimensions: 3
Shape: (3, 3, 5)


In [37]:
## Print 12 from all the dimensions
print('From Dim 1 x3[0,2,1]: {0}\nFrom Dim 2 x3[1,0,1]: {1}\nFrom Dim 3 x3[2,1,1]: {2}'.format(x3[0,2,1],x3[1,0,1],x3[2,1,1]))

From Dim 1 x3[0,2,1]: 12
From Dim 2 x3[1,0,1]: 12
From Dim 3 x3[2,1,1]: 12


In [38]:
x3[0,:,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]], dtype=int8)

In [39]:
x3[:,:,0:3]

array([[[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]],

       [[11, 12, 13],
        [ 1,  2,  3],
        [ 6,  7,  8]],

       [[ 6,  7,  8],
        [11, 12, 13],
        [ 1,  2,  3]]], dtype=int8)

In [40]:
x3[:,:,1:2]

array([[[ 2],
        [ 7],
        [12]],

       [[12],
        [ 2],
        [ 7]],

       [[ 7],
        [12],
        [ 2]]], dtype=int8)

In [41]:
x3[:,:,1:2][2]

array([[ 7],
       [12],
       [ 2]], dtype=int8)

In [42]:
x3[:,:,1:2][2][0]

array([7], dtype=int8)

In [43]:
x3.T

array([[[ 1, 11,  6],
        [ 6,  1, 11],
        [11,  6,  1]],

       [[ 2, 12,  7],
        [ 7,  2, 12],
        [12,  7,  2]],

       [[ 3, 13,  8],
        [ 8,  3, 13],
        [13,  8,  3]],

       [[ 4, 14,  9],
        [ 9,  4, 14],
        [14,  9,  4]],

       [[ 5, 15, 10],
        [10,  5, 15],
        [15, 10,  5]]], dtype=int8)

In [44]:
x4 = np.array(
    
[    [
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],

    [
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],
    
[
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],
    
[
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ]   
    
    ]
)

x4

array([[[[list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])],
         [list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
          list([11, 12, 13, 14, 15])],
         [list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
          list([6, 7, 8, 9, 10])],
         [list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
          list([1, 2, 3, 4, 5])],
         [list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])]],

        [[list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])],
         [list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
          list([11, 12, 13, 14, 15])],
         [list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
          list([6, 7, 8, 9, 10])],
         [list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
          list([1, 2, 3, 4, 5])],
         [list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 3

In [45]:
print('Dimensions: {0}\nShape: {1}\nSize[no of elements in array] :{2}\nMemory Consumption in Bytes(dtype*size): {3}'.format(x4.ndim,x4.shape,x4.size,x4.nbytes))

Dimensions: 4
Shape: (4, 4, 5, 3)
Size[no of elements in array] :240
Memory Consumption in Bytes(dtype*size): 1920


In [46]:
# To reach an element inside x4
x4[1,1,1,1][1]

7