In [1]:
import numpy as np

# NumPy Constants

In [2]:
print('Inifinity (neg,pos): ({0},{1})'.format(np.NINF,np.inf))
print('Zero (neg,pos): ({0},{1})'.format(np.NZERO,np.PZERO))
print('Pi: {0}\nEuler Gamma: {1}\nEpsilon e: {2}'.format(np.pi,np.euler_gamma,np.e))
print('NotANumber: {0}'.format(np.nan))

Inifinity (neg,pos): (-inf,inf)
Zero (neg,pos): (-0.0,0.0)
Pi: 3.141592653589793
Euler Gamma: 0.5772156649015329
Epsilon e: 2.718281828459045
NotANumber: nan


# Array: A collection of similar data types

In [3]:
## Create an N dimensional array with random values
ax = np.empty([3,3], np.uint16)
ax

array([[117, 115, 112],
       [ 49,  48,  46],
       [100, 108, 108]], dtype=uint16)

In [4]:
# To generate a desired array with random numbers less than 1 used if noise must be introduced
randArr = np.random.rand(3,3,3)
randArr

array([[[0.69231132, 0.94233029, 0.86142807],
        [0.2269696 , 0.47024266, 0.24328621],
        [0.0583185 , 0.18355402, 0.73590191]],

       [[0.7995145 , 0.79287536, 0.41736813],
        [0.5254392 , 0.25017577, 0.24221449],
        [0.01970603, 0.47944518, 0.27652013]],

       [[0.39547012, 0.11022923, 0.18287701],
        [0.14105714, 0.25141821, 0.79544104],
        [0.15610505, 0.79848312, 0.93024805]]])

In [5]:
print('size: {0}\nshape: {1}'.format(randArr.size,randArr.shape))

size: 27
shape: (3, 3, 3)


In [6]:
## Create an array with the diagnol as 1
bx = np.eye(5,dtype=np.uint8) 
bx
## Similar to the below
# bx = np.identity(5,dtype=np.uint8) 
# bx

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [7]:
#To change the position of 1
bx1 = np.eye(5, dtype=np.uint8 , k=1)
bx1

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [8]:
#To change the position of 1 down
bx1a = np.eye(5, dtype=np.uint8 , k=-1)
bx1a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [9]:
## To create N dimentional matrix with elements as 1
all1 = np.ones((3,3,5))
all1

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
## To create N dimentional matrix with elements as 0
all0= np.zeros((3,3,5))
all0

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
## To create N dimentional matrix with desired elements
allD = np.full((3,3,3),dtype=np.uint8,fill_value=7)
allD

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]], dtype=uint8)

In [12]:
## Create a Triangular Matrix
tri1 = np.tri(5,5,k=0)
tri1

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [13]:
## Upper Triangle
ut = np.triu(ax,k=0)
ut

array([[117, 115, 112],
       [  0,  48,  46],
       [  0,   0, 108]], dtype=uint16)

In [14]:
## Lower Triangle
lt = np.tril(ax,k=0)
lt

array([[117,   0,   0],
       [ 49,  48,   0],
       [100, 108, 108]], dtype=uint16)

Creation of custom arrays

In [15]:
# Creating a unidirectional array with int16 datatype
x = np.array([1,'2',3,4,5, 6] , np.int8)
x # is equalent to x.view()

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [16]:
print(x[1])
print(x[1].dtype)

2
int8


In [17]:
## shows how many dimensions are there  in the array
x.ndim

1

In [18]:
## Transpose of the matrix
x.T

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [19]:
x2 = np.array([[1,2,3,4,5], [6,7,8,9,10]], np.int8)
x2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

In [20]:
x2.ndim

2

In [21]:
# The data type of internal elements of the array
x2.dtype

dtype('int8')

The number of '[]' mentioned inside the array() method will decide the dimensions of the array, i.e for 
n number of dimensions use nnumber of []

In [22]:
x2.view()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int8)

In [23]:
x2.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]], dtype=int8)

access values with nameofArray[ROWS,COLLUMNS]

In [24]:
# To access the elements of the array, 
print('First row of the array:  {0}\nSecond row of the array: {1}\nits type is {2}'.format(x2[0],x2[1],type(x2[0])))

First row of the array:  [1 2 3 4 5]
Second row of the array: [ 6  7  8  9 10]
its type is <class 'numpy.ndarray'>


In [25]:
## Printing the forth element of second row.
print('Access Method 1 x2[1,3]:  {0}\nAccess Method 2 x2[1][3]: {1}\nAccess Method 3 x2[[1],[3]]: {2}'.format(x2[1,3],x2[1][3],x2[[1],[3]]))
print('Access Type 1:  {0}\nAccess Type 2: {1}\nAccess Type 3: {2}'.format(type(x2[1,3]) , type(x2[1][3]) , type(x2[[1],[3]]) ))

Access Method 1 x2[1,3]:  9
Access Method 2 x2[1][3]: 9
Access Method 3 x2[[1],[3]]: [9]
Access Type 1:  <class 'numpy.int8'>
Access Type 2: <class 'numpy.int8'>
Access Type 3: <class 'numpy.ndarray'>


Slicing data from Array Objects

In [26]:
## Printing the forth element of second row.
print('Access Method 1 x2[1,3]:  {0}\nAccess Method 2 x2[1][3]: {1}\nAccess Method 3 x2[[1],[3]]: {2}'.format(x2[1,3],x2[1][3],x2[[1],[3]]))
print('Access Type 1:  {0}\nAccess Type 2: {1}\nAccess Type 3: {2}'.format(type(x2[1,3]) , type(x2[1][3]) , type(x2[[1],[3]]) ))

Access Method 1 x2[1,3]:  9
Access Method 2 x2[1][3]: 9
Access Method 3 x2[[1],[3]]: [9]
Access Type 1:  <class 'numpy.int8'>
Access Type 2: <class 'numpy.int8'>
Access Type 3: <class 'numpy.ndarray'>


In [27]:
#to print the  first column of the array
x2[:,0]

array([1, 6], dtype=int8)

In [28]:
# Second column
x2[:,1]

array([2, 7], dtype=int8)

In [29]:
#To print the entire first row
x2[0,:]

array([1, 2, 3, 4, 5], dtype=int8)

In [30]:
# To print an element of Second row fourth column
x2[1,3]

9

In [31]:
# To print the elements of first row from second element to fourth element
x2[0,1:4]

array([2, 3, 4], dtype=int8)

In [32]:
# To print the elements of array from all the rows but column 2 to 4
x2[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]], dtype=int8)

In [33]:
## Shape gives rows,columns value
x2.shape

(2, 5)

In [34]:
xNOT3D = np.array([[1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]], np.int8)
xNOT3D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]], dtype=int8)

In [35]:
print('Dimensions: {0}\nShape: {1}'.format(xNOT3D.ndim,xNOT3D.shape))

Dimensions: 2
Shape: (3, 5)


In [36]:
x3 = np.array(
    [
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15] 
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ]
    ]
    , np.int8)
x3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[11, 12, 13, 14, 15],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [ 1,  2,  3,  4,  5]]], dtype=int8)

In [37]:
print('Dimensions: {0}\nShape: {1}'.format(x3.ndim,x3.shape))

Dimensions: 3
Shape: (3, 3, 5)


In [38]:
## Print 12 from all the dimensions
print('From Dim 1 x3[0,2,1]: {0}\nFrom Dim 2 x3[1,0,1]: {1}\nFrom Dim 3 x3[2,1,1]: {2}'.format(x3[0,2,1],x3[1,0,1],x3[2,1,1]))

From Dim 1 x3[0,2,1]: 12
From Dim 2 x3[1,0,1]: 12
From Dim 3 x3[2,1,1]: 12


In [39]:
x3[0,:,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]], dtype=int8)

In [40]:
x3[:,:,0:3]

array([[[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]],

       [[11, 12, 13],
        [ 1,  2,  3],
        [ 6,  7,  8]],

       [[ 6,  7,  8],
        [11, 12, 13],
        [ 1,  2,  3]]], dtype=int8)

In [41]:
x3[:,:,1:2]

array([[[ 2],
        [ 7],
        [12]],

       [[12],
        [ 2],
        [ 7]],

       [[ 7],
        [12],
        [ 2]]], dtype=int8)

In [42]:
x3[:,:,1:2][2]

array([[ 7],
       [12],
       [ 2]], dtype=int8)

In [43]:
x3[:,:,1:2][2][0]

array([7], dtype=int8)

In [44]:
x3.T

array([[[ 1, 11,  6],
        [ 6,  1, 11],
        [11,  6,  1]],

       [[ 2, 12,  7],
        [ 7,  2, 12],
        [12,  7,  2]],

       [[ 3, 13,  8],
        [ 8,  3, 13],
        [13,  8,  3]],

       [[ 4, 14,  9],
        [ 9,  4, 14],
        [14,  9,  4]],

       [[ 5, 15, 10],
        [10,  5, 15],
        [15, 10,  5]]], dtype=int8)

In [45]:
x4 = np.array(
    
[    [
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],

    [
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],
    
[
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ],
    
[
## One Dimenssion
        [
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]            
        ],
##End One Dimenssion        

## Two Dimenssion        
        [       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
        ],
##End of Two Dimenssion        
        
## Three Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ],
##End of Three Dimenssion           

## Fourth Dimenssion        
        [
             [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ],
        [
            [1,2,3,4,5], [6,7,8,9,10] , [11, 12, 13, 14, 15]
        ],
        [
           [11, 12, 13, 14, 15] ,  [1,2,3,4,5] , [6,7,8,9,10]
        ],
        [
            [6,7,8,9,10] , [11, 12, 13, 14, 15] ,  [1,2,3,4,5]
        ],       
        
        [
            [20,21,22,23,24] , [25,26,27,28,29,30] , [31,32,33,34,35]
        ]
            
        ]
## End of Fourth
        
    ]   
    
    ]
)

x4

array([[[[list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])],
         [list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
          list([11, 12, 13, 14, 15])],
         [list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
          list([6, 7, 8, 9, 10])],
         [list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
          list([1, 2, 3, 4, 5])],
         [list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])]],

        [[list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 33, 34, 35])],
         [list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
          list([11, 12, 13, 14, 15])],
         [list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
          list([6, 7, 8, 9, 10])],
         [list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
          list([1, 2, 3, 4, 5])],
         [list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
          list([31, 32, 3

In [46]:
print('Dimensions: {0}\nShape: {1}\nSize[no of elements in array] :{2}\nMemory Consumption in Bytes(dtype*size): {3}'.format(x4.ndim,x4.shape,x4.size,x4.nbytes))

Dimensions: 4
Shape: (4, 4, 5, 3)
Size[no of elements in array] :240
Memory Consumption in Bytes(dtype*size): 1920


In [47]:
# To reach an element inside x4
x4[1,1,1,1][1]

7

Array Manipulation

In [48]:
ar1 = np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
ar2 = ar1.reshape((5,2))
ar2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
# Flattening the matrix/Array [mostly used in signal processing and image processing]
# flatten(...)
#  |      a.flatten(order='C')
#  |      
#  |      Return a copy of the array collapsed into one dimension.
#  |      
#  |      Parameters
#  |      ----------
#  |      order : {'C', 'F', 'A', 'K'}, optional
#  |          'C' means to flatten in row-major (C-style) order.
#  |          'F' means to flatten in column-major (Fortran-
#  |          style) order. 'A' means to flatten in column-major
#  |          order if `a` is Fortran *contiguous* in memory,
#  |          row-major order otherwise. 'K' means to flatten
#  |          `a` in the order the elements occur in memory.
#  |          The default is 'C'.
fl1 = ar2.flatten()
fl1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
fl1.ndim

1

In [52]:
fl2 = x4.flatten()
fl2

array([list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
       list([31, 32, 33, 34, 35]), list([1, 2, 3, 4, 5]),
       list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
       list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
       list([6, 7, 8, 9, 10]), list([6, 7, 8, 9, 10]),
       list([11, 12, 13, 14, 15]), list([1, 2, 3, 4, 5]),
       list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
       list([31, 32, 33, 34, 35]), list([20, 21, 22, 23, 24]),
       list([25, 26, 27, 28, 29, 30]), list([31, 32, 33, 34, 35]),
       list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
       list([11, 12, 13, 14, 15]), list([11, 12, 13, 14, 15]),
       list([1, 2, 3, 4, 5]), list([6, 7, 8, 9, 10]),
       list([6, 7, 8, 9, 10]), list([11, 12, 13, 14, 15]),
       list([1, 2, 3, 4, 5]), list([20, 21, 22, 23, 24]),
       list([25, 26, 27, 28, 29, 30]), list([31, 32, 33, 34, 35]),
       list([20, 21, 22, 23, 24]), list([25, 26, 27, 28, 29, 30]),
       list([31, 32, 33, 3

In [53]:
fl2.ndim

1

In [54]:
xaf = np.array([[1,2,3],[4,5,6]], order='F')
xaf

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
xac = np.array([[1,2,3],[4,5,6]], order='C')
xac

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
xaf == xac

array([[ True,  True,  True],
       [ True,  True,  True]])

In [57]:
id(xaf) == id(xac)

False

In [58]:
## Merging two Series or lists and making them into arrays
vecVal1 = np.arange(6)
vecVal2 = np.arange(6,12)
print(vecVal1,vecVal2, 'type: {0}'.format(type(vecVal1)))

[0 1 2 3 4 5] [ 6  7  8  9 10 11] type: <class 'numpy.ndarray'>


In [59]:
RStk = np.stack([vecVal1, vecVal2], axis=0)
RStk

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [60]:
CStk = np.stack([vecVal1, vecVal2], axis=1)
print('Matrisx: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(CStk,type(CStk),CStk.ndim,CStk.shape,CStk.size))

Matrisx: 
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
Type: <class 'numpy.ndarray'>
Dimensions: 2
Shape: (6, 2)
Size: 12


In [61]:
# To stack the data in multiple ergonomic way D-Stack
DStk = np.dstack([vecVal1, vecVal2])
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(DStk,type(DStk),DStk.ndim,DStk.shape,DStk.size))

Matrix: 
[[[ 0  6]
  [ 1  7]
  [ 2  8]
  [ 3  9]
  [ 4 10]
  [ 5 11]]]
Type: <class 'numpy.ndarray'>
Dimensions: 3
Shape: (1, 6, 2)
Size: 12


In [62]:
#Stacking everything Horizontally
HStk = np.hstack([vecVal1, vecVal2])
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(HStk,type(HStk),HStk.ndim,HStk.shape,HStk.size))

Matrix: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Type: <class 'numpy.ndarray'>
Dimensions: 1
Shape: (12,)
Size: 12


In [63]:
VStk = np.vstack([vecVal1, vecVal2])
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(VStk,type(VStk),VStk.ndim,VStk.shape,VStk.size))

Matrix: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Type: <class 'numpy.ndarray'>
Dimensions: 2
Shape: (2, 6)
Size: 12


In [64]:
randArray1 = np.random.rand(4,4,4)
randArray1

array([[[0.73074805, 0.99619301, 0.34369395, 0.84016738],
        [0.97603664, 0.63804108, 0.67240863, 0.73730487],
        [0.7709081 , 0.12848468, 0.60966725, 0.60069414],
        [0.1586934 , 0.25562619, 0.17088176, 0.63653382]],

       [[0.60997057, 0.17771788, 0.03375434, 0.65730685],
        [0.48353025, 0.29909832, 0.25598247, 0.52397788],
        [0.73086545, 0.09393616, 0.86411347, 0.57949989],
        [0.85073134, 0.69600953, 0.74605616, 0.30006477]],

       [[0.69924188, 0.00967286, 0.71201117, 0.92467291],
        [0.40979764, 0.55775146, 0.27556244, 0.82360604],
        [0.32061146, 0.39122392, 0.49150086, 0.60659507],
        [0.73147831, 0.00931227, 0.52646143, 0.56764001]],

       [[0.97606893, 0.69172378, 0.51574111, 0.24340027],
        [0.40105051, 0.56920842, 0.22265649, 0.14371481],
        [0.69209504, 0.16774409, 0.52960979, 0.5373983 ],
        [0.71937502, 0.52039469, 0.76676371, 0.09965877]]])

In [65]:
## Spliting data into equal parts mostly of the data is in divedents of 2
a,b,c,d = np.split(HStk,4)
print(a,b,c,d)

[0 1 2] [3 4 5] [6 7 8] [ 9 10 11]


In [66]:
a,b,c,d = np.hsplit(randArray1,4)
print(a,b,c,d)

[[[0.73074805 0.99619301 0.34369395 0.84016738]]

 [[0.60997057 0.17771788 0.03375434 0.65730685]]

 [[0.69924188 0.00967286 0.71201117 0.92467291]]

 [[0.97606893 0.69172378 0.51574111 0.24340027]]] [[[0.97603664 0.63804108 0.67240863 0.73730487]]

 [[0.48353025 0.29909832 0.25598247 0.52397788]]

 [[0.40979764 0.55775146 0.27556244 0.82360604]]

 [[0.40105051 0.56920842 0.22265649 0.14371481]]] [[[0.7709081  0.12848468 0.60966725 0.60069414]]

 [[0.73086545 0.09393616 0.86411347 0.57949989]]

 [[0.32061146 0.39122392 0.49150086 0.60659507]]

 [[0.69209504 0.16774409 0.52960979 0.5373983 ]]] [[[0.1586934  0.25562619 0.17088176 0.63653382]]

 [[0.85073134 0.69600953 0.74605616 0.30006477]]

 [[0.73147831 0.00931227 0.52646143 0.56764001]]

 [[0.71937502 0.52039469 0.76676371 0.09965877]]]


In [67]:
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(a,type(a),a.ndim,a.shape,a.size))

Matrix: 
[[[0.73074805 0.99619301 0.34369395 0.84016738]]

 [[0.60997057 0.17771788 0.03375434 0.65730685]]

 [[0.69924188 0.00967286 0.71201117 0.92467291]]

 [[0.97606893 0.69172378 0.51574111 0.24340027]]]
Type: <class 'numpy.ndarray'>
Dimensions: 3
Shape: (4, 1, 4)
Size: 16


In [68]:
a,b,c,d = np.vsplit(randArray1,4)
print(a,b,c,d)

[[[0.73074805 0.99619301 0.34369395 0.84016738]
  [0.97603664 0.63804108 0.67240863 0.73730487]
  [0.7709081  0.12848468 0.60966725 0.60069414]
  [0.1586934  0.25562619 0.17088176 0.63653382]]] [[[0.60997057 0.17771788 0.03375434 0.65730685]
  [0.48353025 0.29909832 0.25598247 0.52397788]
  [0.73086545 0.09393616 0.86411347 0.57949989]
  [0.85073134 0.69600953 0.74605616 0.30006477]]] [[[0.69924188 0.00967286 0.71201117 0.92467291]
  [0.40979764 0.55775146 0.27556244 0.82360604]
  [0.32061146 0.39122392 0.49150086 0.60659507]
  [0.73147831 0.00931227 0.52646143 0.56764001]]] [[[0.97606893 0.69172378 0.51574111 0.24340027]
  [0.40105051 0.56920842 0.22265649 0.14371481]
  [0.69209504 0.16774409 0.52960979 0.5373983 ]
  [0.71937502 0.52039469 0.76676371 0.09965877]]]


In [69]:
print('Matrix: \n{0}\nType: {1}\nDimensions: {2}\nShape: {3}\nSize: {4}'.format(a,type(a),a.ndim,a.shape,a.size))

Matrix: 
[[[0.73074805 0.99619301 0.34369395 0.84016738]
  [0.97603664 0.63804108 0.67240863 0.73730487]
  [0.7709081  0.12848468 0.60966725 0.60069414]
  [0.1586934  0.25562619 0.17088176 0.63653382]]]
Type: <class 'numpy.ndarray'>
Dimensions: 3
Shape: (1, 4, 4)
Size: 16


In [71]:
a

array([[[0.73074805, 0.99619301, 0.34369395, 0.84016738],
        [0.97603664, 0.63804108, 0.67240863, 0.73730487],
        [0.7709081 , 0.12848468, 0.60966725, 0.60069414],
        [0.1586934 , 0.25562619, 0.17088176, 0.63653382]]])

In [76]:
## It litraly flips as per the axis: -ve(Ndim - 1),+ve(Ndim - 1)
np.flip(a, axis=1)

array([[[0.1586934 , 0.25562619, 0.17088176, 0.63653382],
        [0.7709081 , 0.12848468, 0.60966725, 0.60069414],
        [0.97603664, 0.63804108, 0.67240863, 0.73730487],
        [0.73074805, 0.99619301, 0.34369395, 0.84016738]]])

In [79]:
np.flip(a, axis=-1)

array([[[0.84016738, 0.34369395, 0.99619301, 0.73074805],
        [0.73730487, 0.67240863, 0.63804108, 0.97603664],
        [0.60069414, 0.60966725, 0.12848468, 0.7709081 ],
        [0.63653382, 0.17088176, 0.25562619, 0.1586934 ]]])

In [80]:
b

array([[[0.60997057, 0.17771788, 0.03375434, 0.65730685],
        [0.48353025, 0.29909832, 0.25598247, 0.52397788],
        [0.73086545, 0.09393616, 0.86411347, 0.57949989],
        [0.85073134, 0.69600953, 0.74605616, 0.30006477]]])

In [81]:
## Swaps the bottom most N elements to up
np.roll(b,4)

array([[[0.85073134, 0.69600953, 0.74605616, 0.30006477],
        [0.60997057, 0.17771788, 0.03375434, 0.65730685],
        [0.48353025, 0.29909832, 0.25598247, 0.52397788],
        [0.73086545, 0.09393616, 0.86411347, 0.57949989]]])

In [84]:
# BitWise Opperations
x = np.array([0,1,0,1], np.uint8)
y = np.array([0,0,1,1], np.uint8)

print(np.bitwise_and(x,y))
print(np.bitwise_or(x,y))
print(np.bitwise_xor(x,y))
print(np.bitwise_not(y))

[0 0 0 1]
[0 1 1 1]
[0 1 1 0]
[255 255 254 254]
